name: ms-proxy

services:
  proxy:
    image: caddy:2-alpine
    container_name: ms-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - msnetwork

networks:
  msnetwork:
    external: true
