services:
  proxy:
    image: ms-leads/proxy:latest
    build:
      context: .
      dockerfile_inline: |
        FROM traefik:latest
    container_name: proxy
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=ms-network"
      - "--entrypoints.web.address=:3000"
    labels:
      - "traefik.enable=true"
      # Rewrite /proxy/* to /*
      - "traefik.http.middlewares.proxy-strip.stripprefix.prefixes=/proxy"
      # Dashboard static files
      - "traefik.http.routers.traefik-dash.rule=PathPrefix(`/proxy/dashboard`)"
      - "traefik.http.routers.traefik-dash.entrypoints=web"
      - "traefik.http.routers.traefik-dash.service=dashboard@internal"
      - "traefik.http.routers.traefik-dash.middlewares=proxy-strip"
      # API
      - "traefik.http.routers.traefik-api.rule=PathPrefix(`/proxy/api`)"
      - "traefik.http.routers.traefik-api.entrypoints=web"
      - "traefik.http.routers.traefik-api.service=api@internal"
      - "traefik.http.routers.traefik-api.middlewares=proxy-strip"
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ms-network

networks:
  ms-network:
    name: ms-network
    driver: bridge
