services:
  proxy:
    image: ms-leads/proxy:latest
    build:
      context: .
      dockerfile_inline: |
        FROM traefik:latest
    container_name: proxy
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=ms-network"
      - "--entrypoints.web.address=:3000"
    labels:
      - "traefik.enable=true"
      # Strip /proxy prefix
      - "traefik.http.middlewares.proxy-strip.stripprefix.prefixes=/proxy"
      # Replace /proxy/dashboard with /dashboard (для статики)
      - "traefik.http.middlewares.dash-replace.replacepathregex.regex=^/proxy/(.*)"
      - "traefik.http.middlewares.dash-replace.replacepathregex.replacement=/$$1"
      # Dashboard - serve static files
      - "traefik.http.routers.traefik-dash.rule=PathPrefix(`/proxy`)"
      - "traefik.http.routers.traefik-dash.entrypoints=web"
      - "traefik.http.routers.traefik-dash.service=api@internal"
      - "traefik.http.routers.traefik-dash.middlewares=proxy-strip"
      - "traefik.http.routers.traefik-dash.priority=1"
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ms-network

networks:
  ms-network:
    name: ms-network
    driver: bridge
