services:
  proxy:
    image: ms-leads/proxy:latest
    build:
      context: .
      dockerfile_inline: |
        FROM caddy:latest
        COPY Caddyfile /etc/caddy/Caddyfile
    container_name: proxy
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ms-network

networks:
  ms-network:
    name: ms-network
    driver: bridge
