services:
  proxy:
    image: ms-leads/proxy:latest
    build:
      context: .
      dockerfile_inline: |
        FROM traefik:v3.2
    container_name: proxy
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=ms-network"
      - "--entrypoints.web.address=:3000"
    ports:
      - "3000:3000"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ms-network

networks:
  ms-network:
    name: ms-network
    driver: bridge
