services:
  proxy:
    image: ms-leads/proxy:latest
    build:
      context: .
      dockerfile_inline: |
        FROM traefik:latest
    container_name: proxy
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=ms-network"
      - "--entrypoints.web.address=:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=PathPrefix(`/proxy`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.middlewares.dashboard-strip.stripprefix.prefixes=/proxy"
      - "traefik.http.routers.dashboard.middlewares=dashboard-strip"
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ms-network

networks:
  ms-network:
    name: ms-network
    driver: bridge
